### ISSUE TITLE
Parabens pelo projeto

### ISSUE THREAD

**Issue by rossanodr** [joaotextor/busca-processos-judiciais#2]
Parabéns pelo projeto e pela iniciativa, vou tentar contribuir sempre que puder!
Você consegue me responder se atualmente é possivel criar alguma autenticação para acompanhar os processos que correm em sigilo, ou apenas os que são abertos?

**Comment by joaotextor** [comment]
> Parabéns pelo projeto e pela iniciativa, vou tentar contribuir sempre que puder! Você consegue me responder se atualmente é possivel criar alguma autenticação para acompanhar os processos que correm em sigilo, ou apenas os que são abertos?

Obrigado, Rossano!
No momento a API Pública do CNJ não permite a autenticação para consuta de processos em segredo de justiça.
