### ISSUE TITLE
Não consigo usar, estou usando conforme instruções

### ISSUE THREAD

**Issue by lukexp** [joaotextor/busca-processos-judiciais#3]
Estou usando conforme instruções, porém dá o seguinte erro: ambiguous indirect export: BuscaProcesso
O código html que criei de exemplo:
```
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Buscar Processo</title>
</head>
<body>

<script type="module">
  // Importa o módulo
  import {BuscaProcesso} from './node_modules/busca-processos-judiciais/dist/index.js';

  // Função para buscar o processo
  async function buscarProcesso() {
    const busca = new BuscaProcesso(
      "TRF4",
      "APIKey cDZHYzlZa0JadVREZDJCendQbXY6SkJlTzNjLV9TRENyQk1RdnFKZGRQdw==",
    );
    return busca.getCleanResult("50342112220234040000");
  }

  // Chamada da função e manipulação do resultado
  buscarProcesso()
    .then((data) => {
      // Manipula os dados recebidos
      console.log(data);
      // Aqui você pode realizar ações adicionais com os dados, se necessário
    })
    .catch((erro) => {
      // Manipula os erros
      console.log(erro);
    });
</script>

</body>
</html>
````

**Comment by joaotextor** [comment]
Fala, Luke. Tudo beleza?

Muito obrigado por informar esse erro.
Vi que você está fazendo o import fora de um ambiente node (usando seu Browser), por isso não está utilizando um "bare import" e sim uma importação com o caminho completo do arquivo.

A solução para esse bug é bem simples: basta você alterar 2 coisas na sua linha de importação, ficando assim:

`import BuscaProcesso from './node_modules/busca-processos-judiciais/dist/index.mjs'`

Testei seu código aqui e funcionou perfeitamente com essa alteração.

Isso funciona porque:
1. O pacote `BuscaProcesso` é exportado como `default`, então a importação dentro de chaves "{}" gerará conflito.
2. Como você está importando de dentro de um JS module (já que você especificou a propriedade "type" como "module"), a exportação do `BuscaProcesso`, nesse caso, é feita de dentro do arquivo `index.mjs`, que é um ES6 Module (o `index.js` é commom JS).

Estou fechando essa issue. Se precisar abri-la novamente, só me chamar.
