### ISSUE TITLE
metadados

### ISSUE THREAD

**Issue by GabrieelCostaa** [joaotextor/busca-processos-judiciais#5]
Fala joão, pela api é possível buscar o valor do processo pelos metadados? Preciso de processos com o valor maior de 30.000
Valeu

**Comment by joaotextor** [comment]
Oi Gabriel.
Pelo que consta na documentação oficial da API DataJud, o valor da causa não é retornado nas chamadas aos endpoints.

**Comment by blindibrasil** [comment]
Estava buscando a mesma coisa.
Nem na API do DataJud, nem do Diário de Justiça Eletrônico Nacional, em ambas não retorna o valor da causa. 
Estava precisando dessa informação para uma aplicação para não precisar ter que fazer scraping no site dos tribunais.

Caso saiba uma forma de solucionar isso nos diga.
