### ISSUE TITLE
Endpoints

### ISSUE THREAD

**Issue by albertolemos** [joaotextor/busca-processos-judiciais#6]
Os endpoints dos tribunais TJMRS, TJMSP e TJMMG aparentemente estão errados, pois a sigla do tribunal que está na URL não está de acordo com a sigla, conforme os outros endpoints.

![image](https://github.com/joaotextor/busca-processos-judiciais/assets/51492348/7fec4820-4049-4768-80d4-8b392a0b2c88)

**Comment by joaotextor** [comment]
Corrigido no commit [e3953be](https://github.com/joaotextor/busca-processos-judiciais/commit/e3953be673f427a322d3ed5fe3cc51e505aa85d1)
Biblioteca atualizada: [busca-processos-judiciais@1.0.3](https://www.npmjs.com/package/busca-processos-judiciais)

**Comment by joaotextor** [comment]
Obrigado pelo aviso, @albertolemos
