### ISSUE TITLE
Implementação no Codeigniter 4

### ISSUE THREAD

**Issue by RafaelMNogueira** [joaotextor/busca-processos-judiciais#7]
Primeiramente meus parabéns pela contribuição. Gostaria de saber como incluo o projeto dentro do framework Codeigniter 4. Desde já agradeço.

**Comment by joaotextor** [comment]
Bom dia, Rafael. Beleza?
Então, nunca trabalhei com o Codeigniter. Pelo que pesquisei (muito brevemente), não há uma forma de instalar node packages pelo codeigniter usando NPM, como ocorre no laravel. Então, vejo duas alternativas aqui: 
1) instalar o `busca-processos-judiciais` via npm em um projeto separado, ir na pastas node_modules/busca-processos-judiciais, e então copiar o arquivo index.mjs ou index.cjs e colocar dentro da pasta public do seu projeto Codeigniter 4 e a partir dai importar no arquivo php da página que você deseja utilizar.
2) clonar o repositório e fazer a build você mesmo e então copiar o arquivo JS da pasta node_modules, como explicado no item anterior.

Agora, talvez a forma mais fácil mesmo ainda seja fazendo requisições diretamente ao endpoint da API DataJud, sem a necessidade de usar o `busca-processos-judiciais`, e aí fazer o tratamento dos dados que receber manualmente (coisa que a library já faria).

Fico à disposição para outras dúvidas.
Abraço.
