### ISSUE TITLE
Nada que faço da certo

### ISSUE THREAD

**Issue by Leorlsa** [joaotextor/busca-processos-judiciais#8]
**ja tentei de varias formas, ate usando so o resquest da api deles mesmo retorna o value como 0** 
https://static.poder360.com.br/2021/08/decisao-lula-sitio-atibaia-21ago2021.pdf
tentei usar o numero desse processo do Lula de muitos e nenhum retorna value 1 ou sei lá.

**Comment by joaotextor** [comment]
Não sei quanto aos demais processos que você tentou consultar, mas esse dai é uma ação penal com Segredo de Justiça. Logo, não vai retornar na consulta.
![image](https://github.com/user-attachments/assets/66cc3920-7db6-4e8e-a157-2bc89f5fd3da)
